language: node_js

node_js:
  - "6"

sudo: required
dist: trusty

env:
  - TRAVIS_NODE_VERSION="6"

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser

install: 
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
  # - npm run lint

script:
  - npm test
